# frozen_string_literal: true

source 'https://rubygems.org'

gem 'guard-rspec', require: false
gem 'rspec'
gem 'sinatra'
gem 'redcarpet'
gem 'solargraph', group: :development
gem 'readapt', group: :development

